## YAML Template.
---
## Default Configuration for DeathBan

## Time (in seconds) that a player will be banned for after Death
bantime: 300
## Message that is displayed as kick reason to the player
kickmessage: You have died, so you will be unable to play for $time.
## Message that is displayed as the player rejoins while being banned
rejoinmessage: You are banned for $time because you have died before.

mysql: false
## Only change the fields below if mysql is set to true
username: username

password: password

address: localhost

port: 3306